import type { ChatState, IConversation, Message, User } from "../types/chat";

export const mockUsers: Record<string, User> = {
  "user-1": {
    id: "user-1",
    name: "Current User",
    avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    isOnline: true,
  },
  "user-2": {
    id: "user-2",
    name: "John (Landlord)",
    avatar: "https://randomuser.me/api/portraits/men/43.jpg",
    isOnline: true,
    isLandlord: true,
  },
  "user-3": {
    id: "user-3",
    name: "Sarah (Landlord)",
    avatar: "https://randomuser.me/api/portraits/women/33.jpg",
    isOnline: true,
    isLandlord: true,
  },
  "user-4": {
    id: "user-4",
    name: "Mike Johnson",
    avatar: "https://randomuser.me/api/portraits/men/91.jpg",
    isOnline: false,
  },
  "user-5": {
    id: "user-5",
    name: "Emily Parker",
    avatar: "https://randomuser.me/api/portraits/women/12.jpg",
    isOnline: true,
  },
};

export const mockConversations: IConversation[] = [
  {
    id: "conv-1",
    participants: [
      {
        id: "08fe4793-29b1-41a8-bb07-ab0101ef6a3c",
        first_name: "Admin",
        last_name: "User",
        email: "admin@roomfinder.com",
        avatar: null,
        createdAt: null,
        phone: null,
        updatedAt: null,
        status: "true",
        userType: "user",
        userName: "ádfsf",
      },
      {
        id: "2d77e67f-913b-45c8-91b0-ec8d711445f6",
        first_name: "Vi",
        last_name: "Duc Thien",
        email: "vithienym19@gmail.com",
        avatar: null,
        createdAt: null,
        phone: null,
        updatedAt: null,
        status: "true",
        userType: "user",
        userName: "ádfsf",
      },
      {
        id: "9c600637-f106-494c-9c22-2ef90f419873",
        first_name: "Nguyen Van",
        last_name: "A",
        email: "viducthien19@gmail.com",
        avatar: null,
        createdAt: null,
        phone: null,
        updatedAt: null,
        status: "true",
        userType: "user",
        userName: "ádfsf",
      },
    ],
    unread_count: 1,
    isTyping: false,
  },
  {
    id: "conv-2",
    participants: [
      {
        id: "08fe4793-29b1-41a8-bb07-ab0101ef6a3c",
        first_name: "Admin",
        last_name: "User",
        email: "admin@roomfinder.com",
        avatar: null,
        createdAt: null,
        phone: null,
        updatedAt: null,
        status: "true",
        userType: "user",
        userName: "ádfsf",
      },
      {
        id: "2d77e67f-913b-45c8-91b0-ec8d711445f6",
        first_name: "Vi",
        last_name: "Duc Thien",
        email: "vithienym19@gmail.com",
        avatar: null,
        createdAt: null,
        phone: null,
        updatedAt: null,
        status: "true",
        userType: "user",
        userName: "ádfsf",
      },
      {
        id: "9c600637-f106-494c-9c22-2ef90f419873",
        first_name: "Nguyen Van",
        last_name: "A",
        email: "viducthien19@gmail.com",
        avatar: null,
        createdAt: null,
        phone: null,
        updatedAt: null,
        status: "true",
        userType: "user",
        userName: "ádfsf",
      },
    ],
    unread_count: 1,
    isTyping: false,
  },
  {
    id: "conv-3",
    participants: [
      {
        id: "08fe4793-29b1-41a8-bb07-ab0101ef6a3c",
        first_name: "Admin",
        last_name: "User",
        email: "admin@roomfinder.com",
        avatar: null,
        createdAt: null,
        phone: null,
        updatedAt: null,
        status: "true",
        userType: "user",
        userName: "ádfsf",
      },
      {
        id: "2d77e67f-913b-45c8-91b0-ec8d711445f6",
        first_name: "Vi",
        last_name: "Duc Thien",
        email: "vithienym19@gmail.com",
        avatar: null,
        createdAt: null,
        phone: null,
        updatedAt: null,
        status: "true",
        userType: "user",
        userName: "ádfsf",
      },
      {
        id: "9c600637-f106-494c-9c22-2ef90f419873",
        first_name: "Nguyen Van",
        last_name: "A",
        email: "viducthien19@gmail.com",
        avatar: null,
        createdAt: null,
        phone: null,
        updatedAt: null,
        status: "true",
        userType: "user",
        userName: "ádfsf",
      },
    ],
    unread_count: 0,
    isTyping: false,
  },
  {
    id: "conv-4",
    participants: [
      {
        id: "08fe4793-29b1-41a8-bb07-ab0101ef6a3c",
        first_name: "Admin",
        last_name: "User",
        email: "admin@roomfinder.com",
        avatar: null,
        createdAt: null,
        phone: null,
        updatedAt: null,
        status: "true",
        userType: "user",
        userName: "ádfsf",
      },
      {
        id: "2d77e67f-913b-45c8-91b0-ec8d711445f6",
        first_name: "Vi",
        last_name: "Duc Thien",
        email: "vithienym19@gmail.com",

        avatar: null,
        createdAt: null,
        phone: null,
        updatedAt: null,
        status: "true",
        userType: "user",
        userName: "ádfsf",
      },
      {
        id: "9c600637-f106-494c-9c22-2ef90f419873",
        first_name: "Nguyen Van",
        last_name: "A",
        email: "viducthien19@gmail.com",

        avatar: null,
        createdAt: null,
        phone: null,
        updatedAt: null,
        status: "true",
        userType: "user",
        userName: "ádfsf",
      },
    ],
    unread_count: 0,
    isTyping: false,
  },
];

export const mockMessages: Record<string, Message[]> = {
  "conv-1": [
    {
      id: "msg-1",
      senderId: "user-2",
      receiverId: "user-1",
      content: "Hey, is the room still available?",
      timestamp: new Date(Date.now() - 3600000),
      isRead: true,
    },
    {
      id: "msg-2",
      senderId: "user-1",
      receiverId: "user-2",
      content: "Hi, is this room still available?",
      timestamp: new Date(Date.now() - 3000000),
      isRead: true,
    },
    {
      id: "msg-3",
      senderId: "user-2",
      receiverId: "user-1",
      content: "Yes, it is! Would you like to schedule a viewing?",
      timestamp: new Date(Date.now() - 2400000),
      isRead: true,
    },
    {
      id: "msg-4",
      senderId: "user-1",
      receiverId: "user-2",
      content: "That would be great. Is tomorrow afternoon possible?",
      timestamp: new Date(Date.now() - 1800000),
      isRead: true,
    },
    {
      id: "msg-5",
      senderId: "user-2",
      receiverId: "user-1",
      content: "Sure, how about 3 PM?",
      timestamp: new Date(Date.now() - 1200000),
      isRead: false,
    },
  ],
  "conv-2": [
    {
      id: "msg-6",
      senderId: "user-3",
      receiverId: "user-1",
      content: "Hey, is the room still available?",
      timestamp: new Date(Date.now() - 7200000),
      isRead: false,
    },
  ],
  "conv-3": [
    {
      id: "msg-7",
      senderId: "user-1",
      receiverId: "user-4",
      content: "Hi Mike, I saw your listing for the apartment in District 2",
      timestamp: new Date(Date.now() - 86400000),
      isRead: true,
    },
    {
      id: "msg-8",
      senderId: "user-4",
      receiverId: "user-1",
      content:
        "Hello! Yes, it's still available. Would you like more information?",
      timestamp: new Date(Date.now() - 82800000),
      isRead: true,
    },
  ],
  "conv-4": [
    {
      id: "msg-9",
      senderId: "user-1",
      receiverId: "user-5",
      content: "Hi Emily, is your apartment still for rent?",
      timestamp: new Date(Date.now() - 172800000),
      isRead: true,
    },
    {
      id: "msg-10",
      senderId: "user-5",
      receiverId: "user-1",
      content: "Hi there! Yes it is. When would you like to see it?",
      timestamp: new Date(Date.now() - 169200000),
      isRead: true,
    },
  ],
};

export const initialChatState: ChatState = {
  conversations: mockConversations,
  activeConversations: [],
  messages: mockMessages,
  users: mockUsers,
  currentUser: mockUsers["user-1"],
};
